[package]
name = "solana_m0_test_support"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = "=1.0.2"
litesvm = "0.10.0"
solana-keypair = "3.0.1"
solana-message = "3.0.1"
solana-signer = "3.0.0"
solana-transaction = "3.0.2"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }
