[package]
name = "exchange-service"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
application.workspace = true
async-trait.workspace = true
axum = { workspace = true, features = ["json"] }
domain.workspace = true
persistence.workspace = true
runtime.workspace = true
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }

[dev-dependencies]
serde_json.workspace = true
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "postgres", "macros", "migrate"] }
tower = { workspace = true, features = ["util"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }
