[package]
name = "relayer"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anchor-lang.workspace = true
async-trait.workspace = true
settlement_client.workspace = true
solana-hash.workspace = true
solana-keypair.workspace = true
solana-message.workspace = true
solana-signer.workspace = true
solana-transaction = { workspace = true, features = ["bincode"] }
spot_settlement = { path = "../../programs/spot-settlement", features = ["no-entrypoint"] }

[dev-dependencies]
solana-compute-budget-interface.workspace = true
solana-sdk-ids.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }
