[package]
name = "persistence"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
application.workspace = true
anchor-lang.workspace = true
domain.workspace = true
relayer.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "postgres", "json", "macros", "migrate"] }
spot_settlement = { path = "../../programs/spot-settlement", features = ["no-entrypoint"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }
