[package]
name = "settlement_client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anchor-lang.workspace = true
solana-compute-budget-interface.workspace = true
solana-ed25519-program.workspace = true
solana-sdk-ids.workspace = true
spot_settlement = { path = "../../programs/spot-settlement", features = ["no-entrypoint"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }
