[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
token_2022_factory = "59CUZwGMc4xHD4FigFqLyFMsfwaXGPVQuxNNkE9ikzLP"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/dev-wallet.json"

[scripts]
test = "cargo test"

[hooks]
