[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
mock_bridge_receiver = "9BccVRkKCvpjedrsMRoM5vZc9PtvCzfnc2kQgJzPRtun"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/dev-wallet.json"

[scripts]
test = "cargo test"

[hooks]
