[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
modular_issuer = "6zKsNTfMRviuMCxkGS1JgbpPzPJC4ZZJFP1qLEKCdNq6"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/dev-wallet.json"

[scripts]
test = "cargo test"

[hooks]
